### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'gsettings/client_secrets.json'

### ISSUE THREAD

**Issue by daledali** [mtekman/ZoteroGoogleDrive-PDFLinker-Cloud#7]
I'm on windows 10. 

C:\Users\mydjt\OneDrive\Documents\GitHub\ZoteroGoogleDrive-PDFLinker-Cloud\src>run.py <config file>
The syntax of the command is incorrect.

C:\Users\mydjt\OneDrive\Documents\GitHub\ZoteroGoogleDrive-PDFLinker-Cloud\src>python run.py --make-config
Traceback (most recent call last):
  File "run.py", line 19, in <module>
    from Config     import *
  File "C:\Users\mydjt\OneDrive\Documents\GitHub\ZoteroGoogleDrive-PDFLinker-Cloud\src\Config.py", line 189, in <module>
    Kludge() # do it here for flow
  File "C:\Users\mydjt\OneDrive\Documents\GitHub\ZoteroGoogleDrive-PDFLinker-Cloud\src\kludge.py", line 33, in __init__
    f = open(sec,'w')
FileNotFoundError: [Errno 2] No such file or directory: 'gsettings/client_secrets.json'

C:\Users\mydjt\OneDrive\Documents\GitHub\ZoteroGoogleDrive-PDFLinker-Cloud\src>

**Comment by mtekman** [comment]
Try running it from the root directory:

> C:\Users\mydjt\OneDrive\Documents\GitHub\ZoteroGoogleDrive-PDFLinker-Cloud

and then call `python src\run.py`
